baseURL = "https://sajib.xyz/"
languageCode = "en-us"
title = ""
copyright = "Â© SAJIB"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
ignoreErrors = ["error-missing-instagram-accesstoken"]
#disqusShortname = "sajib-xyz"

[params]
	mode="toggle"
	useCDN=false
	subtitle = "Minimal and Clean"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/"


[[params.social]]
name = "GitLab"
icon = "gitlab"
url = "https://gitlab.com/"
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
